# Generated by Django 4.1.7 on 2023-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariosolution',
            name='protected_features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scenariosolution',
            name='protected_values',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
