# Generated by Django 4.1.5 on 2023-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scenariosolution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('user', 'scenario_name')},
        ),
    ]
