# Generated by Django 4.1.5 on 2023-03-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_customuser_password_alter_scenario_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scenariosolution',
            unique_together={('user', 'scenario', 'solution_name')},
        ),
    ]
