# Generated by Django 4.1.5 on 2023-03-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_scenariosolution_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('underfitting', models.FloatField(null=True)),
                ('overfitting', models.FloatField(null=True)),
                ('statistical', models.FloatField(null=True)),
                ('disparate', models.FloatField(null=True)),
                ('equal', models.FloatField(null=True)),
                ('average', models.FloatField(null=True)),
                ('class_balance', models.FloatField(null=True)),
                ('correlated', models.FloatField(null=True)),
                ('model_size', models.FloatField(null=True)),
                ('permutation', models.FloatField(null=True)),
                ('feature', models.FloatField(null=True)),
                ('algorithm', models.FloatField(null=True)),
                ('clever', models.FloatField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('clique', models.FloatField(null=True)),
                ('er_fast', models.FloatField(null=True)),
                ('er_carlini', models.FloatField(null=True)),
                ('er_deep', models.FloatField(null=True)),
                ('loss_sensitivity', models.FloatField(null=True)),
                ('train_test_split', models.FloatField(null=True)),
                ('missing_data', models.FloatField(null=True)),
                ('normalization', models.FloatField(null=True)),
                ('regularization', models.FloatField(null=True)),
                ('factsheet', models.FloatField(null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.scenariosolution')),
            ],
        ),
    ]
