# Generated by Django 4.1.5 on 2023-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_scenario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='LinktoDataset',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='ModelLinks',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='ScenarioName',
        ),
        migrations.AddField(
            model_name='scenario',
            name='response_data',
            field=models.JSONField(null=True),
        ),
    ]
