# Generated by Django 4.1.5 on 2023-04-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_fariness_score_fairness'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy', models.FloatField(null=True)),
                ('globalrecall', models.FloatField(null=True)),
                ('classweightedrecall', models.FloatField(null=True)),
                ('globalprecision', models.FloatField(null=True)),
                ('classweightedprecision', models.FloatField(null=True)),
                ('globalf1score', models.FloatField(null=True)),
                ('classweightedf1score', models.FloatField(null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.scenariosolution')),
            ],
        ),
        migrations.CreateModel(
            name='MetricProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('underfitting_property', models.CharField(max_length=1000, null=True)),
                ('overfitting_property', models.CharField(max_length=1000, null=True)),
                ('statistical_parity_difference_property', models.CharField(max_length=1000, null=True)),
                ('equal_opportunity_difference_property', models.CharField(max_length=1000, null=True)),
                ('average_odds_difference_property', models.CharField(max_length=1000, null=True)),
                ('disparate_impact_property', models.CharField(max_length=1000, null=True)),
                ('class_balance_property', models.CharField(max_length=1000, null=True)),
                ('algorithm_class_property', models.CharField(max_length=1000, null=True)),
                ('correlated_features_property', models.CharField(max_length=1000, null=True)),
                ('model_size_property', models.CharField(max_length=1000, null=True)),
                ('feature_relevance_property', models.CharField(max_length=1000, null=True)),
                ('permutation_feature_importance_property', models.CharField(max_length=1000, null=True)),
                ('normalization_property', models.CharField(max_length=1000, null=True)),
                ('missing_data_property', models.CharField(max_length=1000, null=True)),
                ('regularization_property', models.CharField(max_length=1000, null=True)),
                ('train_test_split_property', models.CharField(max_length=1000, null=True)),
                ('factsheet_completeness_property', models.CharField(max_length=1000, null=True)),
                ('confidence_score_property', models.CharField(max_length=1000, null=True)),
                ('clique_method_property', models.CharField(max_length=1000, null=True)),
                ('clever_score_property', models.CharField(max_length=1000, null=True)),
                ('er_fast_gradient_attack_property', models.CharField(max_length=1000, null=True)),
                ('er_carlini_wagner_attack_property', models.CharField(max_length=1000, null=True)),
                ('er_deepfool_attack_property', models.CharField(max_length=1000, null=True)),
                ('loss_sensitivity_property', models.CharField(max_length=1000, null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.scenariosolution')),
            ],
        ),
    ]
