# Generated by Django 4.1.5 on 2023-01-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_scenariosolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariosolution',
            name='trainingdata',
            field=models.FileField(upload_to='files'),
        ),
    ]
