# Generated by Django 4.1.5 on 2023-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_scenariosolution_trainingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariosolution',
            name='trainingdata',
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='FactsheetFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='ModelFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='ScenarioName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='SolutionDescription',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='SolutionName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='Targetcolumn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='TestFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='TrainingFile',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
