# Generated by Django 4.1.5 on 2023-01-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_scenariouser_user_id_scenariouser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariouser',
            old_name='email',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='scenariouser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='scenariouser',
            name='password',
        ),
    ]
