# Generated by Django 4.1.5 on 2023-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_rename_email_scenariouser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariouser',
            name='is_admin',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
