# Generated by Django 4.1.5 on 2023-02-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_scenariouser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariouser',
            name='is_admin',
        ),
    ]
