# Generated by Django 4.1.5 on 2023-02-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_remove_scenariouser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariouser',
            name='is_admin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
