# Generated by Django 4.1.5 on 2023-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_scenariouser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariouser',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
