# Generated by Django 4.1.5 on 2023-02-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_scenariouser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariosolution',
            name='Favoutcome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='Protectedfeat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scenariosolution',
            name='Protectedval',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
