# Generated by Django 4.1.5 on 2023-02-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_scenariosolution_outlierdatafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondstock',
            name='user',
        ),
        migrations.DeleteModel(
            name='FirstStock',
        ),
        migrations.DeleteModel(
            name='SecondStock',
        ),
    ]
